# This example uses a host mounted directory that is created/used relative to this
# location of this compose file.

version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      PACKAGE_BACKUP_KEEP: 2
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "MINECRAFT"
      ALLOW_CHEATS: "true"
      MAX_PLAYERS: 2
      ONLINE_MODE: "true"
      ALLOW_LIST_USERS: "xboxid"
      MAX_THREADS: 2
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
